name = "EDDPTools"
uuid = "fe14d997-9d7c-4cd1-a64e-b0030953cfa2"
authors = ["Bonan Zhu <zhubonan@outlook.com>"]
version = "0.1.0"

[deps]
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
CellBase = "01ff7365-e1e2-4ed5-aabe-f1c451dd6d4e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
EDDP = "cffdf5dc-aa8e-4f15-840d-78559bc58d9d"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Flux = "0.13"
julia = "1.7"
